### ISSUE TITLE
Get product group to each product detail page

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#101]
Replace 'Product Category' with its product item group.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/70f21f7c-47b6-481a-b5dc-45f037c2d023)

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/0b9a84ef-19a3-4fe4-87eb-633ad6992fd7)

**Comment by AnatholyB1** [comment]
this is static code, 10 min needed, @chomchuen  @John-zaviago

**Comment by AnatholyB1** [comment]
@chomchuen  ready for review

**Comment by chomchuen** [comment]
✅
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/81804acd-5c3e-4891-b075-5bbf235b346d)
