### ISSUE TITLE
Payment method of 'PAID' & 'CANCELLED' SINV

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#120]
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/924810bf-3c8c-44be-8b61-ba24f4da3687)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/cc8c2efc-8afc-4fb5-8a9b-5ade6b9e9f3a)

**Comment by MarkSuttirak** [comment]
I have modified the condition of the payment method display when the status is 'Overdue', 'Cancelled', or 'Paid'
It should not show the payment method selection if the status is 'Overdue', 'Cancelled'. Also, the payment method should not be changed if the status is 'Paid'.

**Comment by chomchuen** [comment]
we doesn't have 'กำลังตรวจสอบการชำระเงิน' or 'พร้อมจัดส่ง' status.
Now, if order turned to 'PAID', payment method will can't be selected anymore and shows payment method of current order.✅
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/d1a9f73d-216c-44d6-ae09-c80c574ded32)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/2047e275-b8fd-4066-b5b4-d417d43ef2e1)


For canceled status✅
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/83d81752-da84-45fb-8f5b-97f9a86c8237)
