### ISSUE TITLE
Storefront - skaleton loading but can click check out

### ISSUE THREAD

**Issue by primSirirnit** [zaviagodev/e_commerce_store#131]
ในหน้า check out ในระหว่างที่คำนวณค่าจัดส่งอยู่ และมี skeleton อยู่ ปุ่มชำระเงิน ไม่ควรกดได้ค่ะ 
ให้เพิ่ม loading ในปุ่มชำระเงินตอนที่มี skeleton เกิดขึ้นในหน้า checkout นะคะ 
https://www.loom.com/share/8df64047c6d646c1b5a013a25425beb9?sid=0af078f1-ddce-4a6e-a698-95343e8b388f

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/3502d896-8a76-4243-9171-79909782175d)

**Comment by MarkSuttirak** [comment]
Fixed the disabled button when partially or completely showing skeletons
