### ISSUE TITLE
Implement Placeholder Image for Products Without Images in Storefront

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/e_commerce_store#22]
**Issue Title:** Implement Placeholder Image for Products Without Images in Storefront

**Issue Description:**
To enhance the visual consistency and user experience on the storefront, we need to implement a placeholder image for products that do not have images in the database. Currently, when a product lacks an image, the operating system's default broken image icon is displayed, negatively impacting the visual aesthetics.

**Enhancements:**

1. **Placeholder Image for Products:**
   - Introduce a placeholder image to be displayed for products without images in the database.
   - Design the placeholder image to be visually appealing and suitable for various product categories.

**Implementation Steps:**

1. **Design Placeholder Image:**
   - Create a visually appealing placeholder image that can serve as a generic representation for products without specific images.

2. **Integrate Placeholder Image Logic:**
   - Implement logic to detect products without images.
   - When a product lacks an image, dynamically display the designed placeholder image instead of the default broken image icon.

**Expected Outcome:**
- Users will experience a more visually consistent and aesthetically pleasing storefront, even for products without specific images.
- The placeholder image will provide a better representation and improve the overall user experience.

**Additional Information:**
- Consider using a lightweight and universally applicable design for the placeholder image.
- Test the implementation across different product categories to ensure the placeholder image suits various contexts.

**Priority:** Medium

**Assignees:** [Assign appropriate team member]

**Labels:**
- Storefront
- User Experience
- Visual Consistency

---

**Action Plan:**
1. Assign the issue to a team member specializing in frontend development and user experience.
2. Design a visually appealing placeholder image suitable for various product categories.
3. Implement logic to detect products without images and dynamically display the placeholder image.
4. Test the implementation across different product categories to ensure visual consistency.
5. Ensure the placeholder image is lightweight and universally applicable.
6. Update documentation to inform users about the improved visual representation.
7. Communicate updates to the team and stakeholders.
8. Document the implementation details for future reference.

---

*How to Test:*
- Verify that products without specific images now display the designed placeholder image.
- Confirm that the placeholder image is visually appealing and suits various product categories.

**Comment by deviljutt** [comment]
its done also have added the field from where you can add custom default

![Image](https://github.com/zaviagodev/e_commerce_store/assets/29252752/c750a1d9-9b62-4d81-bb8e-b643417275e7)

 image

**Comment by John-zaviago** [comment]
Place holder is done -
