### ISSUE TITLE
Storefront Check out - Add Shipping price by weight

### ISSUE THREAD

**Issue by primSirirnit** [zaviagodev/e_commerce_store#34]
Add new shipping pricing by  weight in check out page 

Note : Mark working on Design / Nabeel working on Backend 

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/834ab0d9-bb80-4487-a4aa-952b61ff76d9)

**Comment by chomchuen** [comment]
**Condition**

If "calculate based on" = **Net Weight** or **Net Total**, please display '**เลือกเพื่อคำนวณค่าจัดส่ง**'.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/048939b2-b572-4f88-9e03-d4a26bacc901)

@primSirirnit  รบกวนปริมเช็คความยาวของคำนิดนึงนะคะ ถ้า "เลือกเพื่อคำนวณค่าจัดส่ง" ยาวไปอาจจะต้องตัดบรรทัดลงมา เลยอยากให้กำหนดว่าจะให้ text นี้มีความยาวเป็นกี่ % ของปุ่มนะคะ

**Comment by MarkSuttirak** [comment]
There needs to be the 'calculated_based_on' key on the shipping rule object. But now, it shows only name, shipping amount, and shipping rule type. Moreover, the options of 'calculated based on' are 'Fixed', 'Net Total', and 'Net Weight'. If the shipping rule calculation is set as 'Net Weight', I can change the text such as ฿0 to 'เลือกเพื่อคำนวณค่าจัดส่ง'.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/a4d2004e-9cf3-4bdb-ad75-6d4f57bcb512)

![Image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/7aeaf2e7-c177-41c4-9d27-4358f2422792)

**Comment by primSirirnit** [comment]
forwarded to Nabiu

**Comment by chomchuen** [comment]
Assigned this to Nabeel already (ref:https://github.com/zaviagodev/e_commerce_store/issues/63)
For the difference between those 2 fields is default and customized field. The new one is customized field and it's not ready to use yet. So please ignore this field😅
