### ISSUE TITLE
Implement Dynamic Global Navigation Menu Configuration

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/e_commerce_store#4]
**Issue Title:** Implement Dynamic Global Navigation Menu Configuration

**Issue Description:**
Need dynamic function that allows users to configure the global navigation menu. This feature will enable users to add links that either navigate to pages within the same site or link to external websites, offering flexibility in creating a customized and dynamic navigation structure.

**Instructions:**
- Implement a configuration section in the system settings for the global navigation menu.
- Allow users to add links, specifying whether the link directs to pages within the same site or external websites.
- Provide options for users to customize link labels and order.
- Ensure proper validation to handle internal and external links appropriately.

**Expected Behavior:**
- Users can add, edit, and remove links in the global navigation menu.
- Each link can be configured to navigate to pages within the site or external websites.
- The order and labels of the links are customizable.

**Comment by AnatholyB1** [comment]
User is able to add / delete/ update and view created links, internal or external. no icon.
