### ISSUE TITLE
Can't login to Storefront

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#47]
Nothing happens after pressing login button.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/d7aee4b1-fa42-4c48-8200-0da217fdc22e)

**Comment by deviljutt** [comment]
This is complete the issue was related to Validation

https://www.loom.com/share/714c2428acab4832836eed5be5bca2be?sid=97804d3e-8b1d-41f9-8742-d00a41799d14

**Comment by John-zaviago** [comment]
@chomchuen  I gave it a test spin, but could you do a double-check on your end? Try it out in both regular and incognito modes, and throw in a couple of different accounts just to be thorough. Let's make sure that login hiccup is smoothed out completely. Appreciate your help! 👍

**Comment by chomchuen** [comment]
I confirm that I was able to login in the morning. but now I can't both sign-in & sign-up

**Comment by John-zaviago** [comment]
![image](https://github.com/zaviagodev/e_commerce_store/assets/62638753/a2382e37-0a66-4aa2-9c4f-e3f5f4e5ac61)
@chomchuen please report your finding here thank

**Comment by chomchuen** [comment]
I didn't face this issue anymore and I'm going to close this issue.🙏
