### ISSUE TITLE
Wrong Grand total in Checkout page

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#48]
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/45971cef-e0be-4244-983a-b33e0afba49d)

**Comment by chomchuen** [comment]
This problem happened in the **quotation doctype**.

Only 1st row products (which is old products) that have correct grand total on checkout.
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/4d18537b-125a-46b8-9d6c-4e4fa5301ee4)

I tried to add same product manually in Quotation and price was there.
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/b8802809-7a10-4d86-a3a9-b8e854abbc1e)

**Comment by deviljutt** [comment]
@chomchuen can you please test this thing

**Comment by chomchuen** [comment]
**Resolved✅**

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/933a6d63-17b9-4c53-9f9d-849e664ce3b8)

**Comment by chomchuen** [comment]
This happening again.
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/7523ce0f-c37c-43a6-8949-696f876378c7)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/fa65d7ad-da5d-4187-97c0-5a22ccf2eb3f)

**Comment by John-zaviago** [comment]
tested in private mode in thita account. - but need to test with the flow suggested by @deviljutt

**Comment by John-zaviago** [comment]
@chomchuen waiting for comment from you of the review

**Comment by chomchuen** [comment]
@deviljutt Accounts that used to face this issue will still experience it, is this correct? New accounts will not encounter this issue. Can you confirm?

**Comment by deviljutt** [comment]
@chomchuen can you check this i have fix the calculation issue
