### ISSUE TITLE
Flickering issue on item image in Checkout

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/e_commerce_store#50]
As seen in video, the item image keep flickering in the checkout page

https://www.loom.com/share/d0d80e3c5bf749378f691d0b938eba22

**Comment by deviljutt** [comment]
@MarkSuttirak can you take a look into this its simple just add skelton during loading

**Comment by John-zaviago** [comment]
Moved to Mark. / @MarkSuttirak when you done with the text fixing from the business team, check this issue and fix it.

**Comment by John-zaviago** [comment]
This seem to be fix. Good job!
