### ISSUE TITLE
Fresh users aren't able to checkout.

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#62]
Fresh users (who just registered and want to checkout immediately) aren't able to checkout. 
I need to refresh the page 1 times to resolved this issue.

Ref.
https://www.loom.com/share/6bb9a6f459d34b63b3243164a8fd6a53?sid=7620104d-b917-4a12-af4d-16202ae6c733

**Comment by chomchuen** [comment]
Can you check again pls? @deviljutt 

https://www.loom.com/share/3688c4f5d31a429c8cbac9a29923a821?sid=f0dc290f-80a2-49a2-8396-87962649ceb5

**Comment by John-zaviago** [comment]
Need to be fix before 5 feb 2024

**Comment by chomchuen** [comment]
not happen just for only newly user but every users that logged in to the store faced this issue.

**Comment by deviljutt** [comment]
its also completed

**Comment by chomchuen** [comment]
Will check this again after signup is fixed.
but for old customer didn't face this anymore.

**Comment by chomchuen** [comment]
Tested with newly account and can checkout at 1st attempt.✅
