### ISSUE TITLE
Storefront website setting doctype functionality.

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#64]
Please check feature that just have added here.
It doesn't work.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/a2828745-7013-458e-8e6d-d962e239735a)

**Comment by deviljutt** [comment]
@chomchuen  please check this

**Comment by chomchuen** [comment]
**Resolved.**

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/fa360515-ba6c-4a01-b20a-a4826f3c25e9)
