### ISSUE TITLE
Storefront pagination

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#65]
2 points pending.

- [x] 1. pagination url.
- [x] 2. product don't display correctly.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/64731d09-b32d-4c7f-8744-a7676deb4c3b)

**Comment by deviljutt** [comment]
@chomchuen can you please check this its completed

**Comment by chomchuen** [comment]
Fixed.✅

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/c1b7f9c3-3398-425c-b485-0b215cce9876)

**Comment by chomchuen** [comment]
Found cart problem related with pagination. Please check the detail from video.

https://www.loom.com/share/6571cd3e13c546e7b898736fe403819a?sid=aa5b8a62-d32f-4453-a82e-6680a32dac90

**Comment by John-zaviago** [comment]
need to interview @chomchuen as a users

**Comment by chomchuen** [comment]
@deviljutt still facing this issue.

**Comment by John-zaviago** [comment]
Let skip the pagination number in the slug or in URL for now. it good to have but not must have. if user need to share link, they will share item specifilink any way i guess.

**Comment by John-zaviago** [comment]
https://www.loom.com/share/6571cd3e13c546e7b898736fe403819a

for this issue. - please fix it.

**Comment by John-zaviago** [comment]
@deviljutt 

![Image](https://github.com/zaviagodev/e_commerce_store/assets/62638753/c87994dc-496f-4812-b3cf-a539415a8222)

 seem like these function does not work in an expected way for pagination system.

**Comment by deviljutt** [comment]
@chomchuen above issue is fixed please check

![Image](https://github.com/zaviagodev/e_commerce_store/assets/29252752/611ecddf-f14a-4847-8de7-b99dca725481)

**Comment by chomchuen** [comment]
1. Issue in this Loom is persisting.
https://www.loom.com/share/6571cd3e13c546e7b898736fe403819a

2. Pagination '1' resolved.


![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/825e1331-d2ab-4b10-a505-cce88fbc7a55)

**Comment by deviljutt** [comment]
@chomchuen can you check Previous/Back button again ?

**Comment by chomchuen** [comment]
Please check number of the page in url. 
https://www.loom.com/share/17f5e03c7c2d43edb16c9da2c95e0c30?sid=67ff4984-5bc6-4151-bd57-f3ea4cc2ab2c

**Comment by chomchuen** [comment]
Next page button became enable again after refresh the last page.

https://www.loom.com/share/069fde9188c84e0fa58ff968526021d0?sid=17600974-a829-4e2a-a8be-4479e38cf863

**Comment by chomchuen** [comment]
@deviljutt Next button should disable if it's last page in the store.😭

**Comment by chomchuen** [comment]
https://apps.hosting.zaviago.com/store/home/all%20items/4

I'm still able to go to page 5 from page 4🤔.
Next page button wasn't disabled yet.

**Comment by chomchuen** [comment]
Fixed.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/4a3b5a03-b611-4122-a60d-0544b66c1fc1)
