### ISSUE TITLE
Hide Checkout/Hide Wish Setting.

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#67]
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/2ee95ce0-ae21-45be-8a59-e73b3042d750)
----
### Hide Checkout

--> **Objective**: 'Add to Cart' button should be hidden and Customer can't add any product to cart.

--> **Now**: Cart icon is hidden but 'Add to Cart' button isn't. **Please hide 'Add to Cart' button from each item.**

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/432ab371-6d12-4c9f-9c69-59400460d949)

----

### Hide wish

--> **Objective**: Heart icon should be hidden from everywhere in store.

--> **Now**: Customer are still able to access the wishlist from cart. **Please hide 'heart icon' from cart as well.**

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/52fdc3b6-a949-4694-ab0a-db327452dc63)

**Comment by deviljutt** [comment]
@chomchuen can you please also check this

**Comment by friendthita** [comment]
checked all cart and wish ka. @chomchuen

**Comment by friendthita** [comment]
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098850/ac05f38a-796d-4565-9b30-51b8ab64d13c)

While hide 'Add to cart' I can able add to cart on hover state as images above. Please recheck.

**Comment by John-zaviago** [comment]
@deviljutt informed that it been done and asked @chomchuen for review

**Comment by chomchuen** [comment]
I want to add some condition to "Hide/Show Cart" setting because I just got the confirmation to use the same button for "Add to cart" and "Contact Store".

- [ ] Bring button back for 'Hide Cart' option and set the condition/function to the 'Hide Cart' button.
- [ ] Change how we set text button for 'Show Cart'

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/d94347f6-6650-4bf6-8527-5013f595f08e)

**Comment by John-zaviago** [comment]
move to muzzalmal tasks -

**Comment by AnatholyB1** [comment]
so the default taxe is already done, in english, but we still miss the action in the doctype of hiding the input when hideCart is selected or not. I'll need to speak a bit with muzameel a bit but i think 1h is enough

**Comment by AnatholyB1** [comment]
@chomchuen the implementation of hide and mandatory is done, check the behaviour in the website and tell me if it's like you want

**Comment by chomchuen** [comment]
@AnatholyB1 Let's talk about expectation of this function in the meeting today.👌

**Comment by AnatholyB1** [comment]
Okay sure

**Comment by AnatholyB1** [comment]
@chomchuen  ready for review

**Comment by John-zaviago** [comment]
@chomchuen have you check this? since the respond was 2 days ago

**Comment by chomchuen** [comment]
Sorry for the delayed response.  I've checked this and confirmed that it meets 100% of the requirements.
