### ISSUE TITLE
Delete existing address

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#68]
Now, we don't let customer delete addresses from their account and show all addresses that  belong to them. 

What we need to do is.

1. Add delete button and confirmation to delete popup.
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/0ee0c35c-c047-4afd-a2c8-d553605c3702)

2. Create delete button's function. Its function is equal to 'Disabled' checkbox.
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/5ecb701f-2db0-4090-8e22-c010c14407cc)

3. Filter only 'Non Disabled' addresses to front-end.

The address that have disabled will unable to recover forever from customer's side.

**Comment by deviljutt** [comment]
@MarkSuttirak can you please add these button or cross here

**Comment by John-zaviago** [comment]
@MarkSuttirak added the button - now need to make dynamic - expected timeline -10 -20 min

**Comment by deviljutt** [comment]
@chomchuen its completed

**Comment by chomchuen** [comment]
Approved✅

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/eec626ef-cc9c-4746-a58a-e89304187da2)
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/e346dbaa-3f8c-4bcc-8002-3f3c32d04670)
