### ISSUE TITLE
Storefront - can't reduce the number of products

### ISSUE THREAD

**Issue by primSirirnit** [zaviagodev/e_commerce_store#73]
Can't reduce the number of products
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120098635/299a1155-ad89-41a8-ab31-c414653a1eb8)

**Comment by chomchuen** [comment]
@primSirirnit Please check and confirm if this issue still persisting or not nakaa👀

**Comment by primSirirnit** [comment]
Now , this work kaa
