### ISSUE TITLE
Auto login after registration

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#74]
Automatic Login after Registration.

- **Upon successful registration, users should be automatically logged in to their newly created accounts without requiring additional login steps.**

- [x]  (Mark completed adding this step✅)Users should receive a confirmation message indicating that they have been automatically logged in after completing the registration process.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/7154674a-0331-4713-a5a1-7fb172050ca3)

**Comment by deviljutt** [comment]
@chomchuen can you please test this

**Comment by chomchuen** [comment]
@deviljutt 
Login doesn't work both manual and automatic.
https://www.loom.com/share/9e4cdc9d6c2a45bfa3f9e4285cfcdbc9

**Comment by chomchuen** [comment]
**Resolved✅**

https://www.loom.com/share/bcd68f76594f43ef808bfe6d809cce19?sid=1a46695f-09df-4330-b479-22a1a73ce788
