### ISSUE TITLE
Get data to the order history detail page.

### ISSUE THREAD

**Issue by chomchuen** [zaviagodev/e_commerce_store#89]
Need 3 more data to order history detail page.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/41a98aba-1565-4020-bcbc-f4f27c7f39f7)

**Comment by deviljutt** [comment]
@chomchuen can you please check this also

![Image](https://github.com/zaviagodev/e_commerce_store/assets/29252752/90ec8b8c-8967-45f4-9813-3a47a93fa06f)

**Comment by chomchuen** [comment]
@MarkSuttirak Please check currency format.
Remove **`**
Set decimal to 2 places. 4268.2 -> 4268.20
1000 -> 1000.00

**Comment by MarkSuttirak** [comment]
For the currency format, I have already fixed, but the code is not pushed to the production.
![image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/b9c384d4-95e4-4a92-b651-46c58d73e006)

**Comment by chomchuen** [comment]
Can't check due to this👀.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/cbd61f94-7459-4e35-81fb-82664be4bab9)

**Comment by chomchuen** [comment]
Products that are not located on the first page will not be displayed on the order detail page.

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/6b2c8c78-53b4-4bf9-989d-b23c8385da96)

**Comment by AnatholyB1** [comment]
i'll need to speak with a nabil a little bit, but i think 1h is enough

**Comment by AnatholyB1** [comment]
@chomchuen  can u give me an order that's not working ?
i have to check few things before pushing the resolution

**Comment by chomchuen** [comment]
**ACC-SINV-2024-00199**. However you can reproduce the issue by buying any product from the 2nd page and so on.

username:
```
paramita.sri@gmail.com
```
pass:
```
zaviago.com
```



![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/58fe3a5e-48df-456b-85b2-97294c14b05c)

**Comment by AnatholyB1** [comment]
@chomchuen  this need review, it should be working, check if its working when u reloading the page, if not i know why it will take me 10 min

**Comment by chomchuen** [comment]
Issue is still persisting. @AnatholyB1

**Comment by AnatholyB1** [comment]
@chomchuen ok let me check

**Comment by AnatholyB1** [comment]
@chomchuen  ready for revise

**Comment by chomchuen** [comment]
Fixed. Thanks!

![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/25d23e08-10e5-4077-ad57-c428c692db10)
