### ISSUE TITLE
Consult - add the logo for banks and payment methods

### ISSUE THREAD

**Issue by MarkSuttirak** [zaviagodev/e_commerce_store#99]
### Promptpay
![image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/8c2c54c9-e0dc-4adf-8e42-6a9677110dc5)

### Bank list
![image](https://github.com/zaviagodev/e_commerce_store/assets/116248336/700e1781-5a7a-4f3b-b2a6-33075f63a717)

From the images above, I have a question about uploading the logo of each bank at the front of the bank details, which method do you think it is better to add the logo?

1. Add the logo by using if else statement on the code like this:
   if (bank === 'bank-0'){
        setImage(banklogo)
   } else if (bank === 'bank-1'){
        setImage(banklogo2)
   } else if ...
 
 2. From 'bank' and the payment setting on 'storefront website settings' doctype, should the upload image field be added so that I can fetch the data to the code? If yes, on which doctype should the upload image field be added?

**Comment by chomchuen** [comment]
Bank logo will display on the payment step 3.
Bank logo will change according to bank that set up in storefront website setting doctype.

**Expectation:**
![Image](https://github.com/zaviagodev/e_commerce_store/assets/120152434/506043a2-072b-4892-b547-398f84adfe5f)
